### ISSUE TITLE
The API is now timing out

### ISSUE THREAD

**Issue by LukeGary462** [markhillard/icanhazdadjoke#1]
I have been using this API to give my lab some giggles, but requests via the API and the website seem to be down :(

**Comment by markhillard** [comment]
@LukeGary462, glad you're having some fun with it! I just tried navigating to https://icanhazdadjoke.com/ and I got a timeout error as well. Guess they're having some issues. Hopefully it will come back up soon.

**Comment by markhillard** [comment]
@LukeGary462, looks like it's back up now.
